spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/dormitory
    username: root
    password: root
server:
  servlet:
    context-path: /api
sa-token:
  token-name: token